# Generated by Django 3.2.12 on 2022-03-23 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Provision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "python_version",
                    models.CharField(max_length=10, verbose_name="Python version"),
                ),
                (
                    "django_version",
                    models.CharField(max_length=10, verbose_name="Django version"),
                ),
                (
                    "project_name",
                    models.CharField(max_length=20, verbose_name="Project name"),
                ),
            ],
            options={
                "verbose_name": "Provision",
                "verbose_name_plural": "Provision List",
                "db_table": "provision",
            },
        ),
    ]
